- name: Install required packages
  yum:
    name: 
      - vim
      - git
      - curl
      - wget
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Prevent preflight warning with kubeadm init
  systemd:
    name: kubelet
    state: stopped
    enabled: yes
    daemon_reload: yes
  ignore_errors: yes
