- name: Delete CRI-O repo
  yum_repository:
    name: "CRI-O"
    state: absent

- name: Delete Upstream repo
  yum_repository:
    name: "UpstreamContainers"
    state: absent

- name: Delete CentOS7 repo
  yum_repository:
    name: "CentOS7"
    state: absent

- name: Delete CRI-O packages
  yum:
    name:
      - container-selinux
      - runc
      - cri-o
      - cri-tools
    state: absent
