- name: Apply weave-network (quick and dirty)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  args:
    executable: /bin/bash
  when: "{{ network_plugin }}" == "weave"
