- name: Remove Kubernetes Repo
  yum_repository:
    name: Kubernetes
    state: absent

- name: Remove installed packages
  yum:
    name:
      - wget
      - kubelet
      - kubeadm
      - kubectl
    state: absent
