- name: Remove Kubernetes Repo
  yum_repository:
    name: Kubernetes
    state: absent

- name: KubeADM internal remove
  shell: kubeadm reset --force

- name: Remove custom directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /root/.kube
    - /etc/cni/net.d
    - /etc/kubernetes

- name: Remove installed packages
  yum:
    name:
      - wget
      - kubelet
      - kubeadm
      - kubectl
    state: absent
